version: '3.1'
services:
  API:
    image: 'umaidila/docker-investappatb'
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/invest
      - SPRING_DATASOURCE_USERNAME=invest
      - SPRING_DATASOURCE_PASSWORD=invest
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update/
  PostgreSQL:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=invest
      - POSTGRES_USER=invest
      - POSTGRES_DB=invest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U invest" ]
      interval: 10s
      timeout: 5s
      retries: 5
